# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.pushButton_Random = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Random.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Random.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Random.setFont(font)
        self.pushButton_Random.setObjectName("pushButton_Random")
        self.gridLayout_2.addWidget(self.pushButton_Random, 0, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(16)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_01 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_01.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_01.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_01.setCheckable(True)
        self.pushButton_01.setObjectName("pushButton_01")
        self.horizontalLayout.addWidget(self.pushButton_01)
        self.pushButton_02 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_02.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_02.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_02.setCheckable(True)
        self.pushButton_02.setObjectName("pushButton_02")
        self.horizontalLayout.addWidget(self.pushButton_02)
        self.pushButton_03 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_03.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_03.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_03.setCheckable(True)
        self.pushButton_03.setObjectName("pushButton_03")
        self.horizontalLayout.addWidget(self.pushButton_03)
        self.pushButton_04 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_04.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_04.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_04.setCheckable(True)
        self.pushButton_04.setObjectName("pushButton_04")
        self.horizontalLayout.addWidget(self.pushButton_04)
        self.pushButton_05 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_05.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_05.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_05.setCheckable(True)
        self.pushButton_05.setObjectName("pushButton_05")
        self.horizontalLayout.addWidget(self.pushButton_05)
        self.pushButton_06 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_06.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_06.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_06.setCheckable(True)
        self.pushButton_06.setObjectName("pushButton_06")
        self.horizontalLayout.addWidget(self.pushButton_06)
        self.pushButton_07 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_07.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_07.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_07.setCheckable(True)
        self.pushButton_07.setObjectName("pushButton_07")
        self.horizontalLayout.addWidget(self.pushButton_07)
        self.pushButton_08 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_08.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_08.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_08.setCheckable(True)
        self.pushButton_08.setObjectName("pushButton_08")
        self.horizontalLayout.addWidget(self.pushButton_08)
        self.pushButton_09 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_09.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_09.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_09.setCheckable(True)
        self.pushButton_09.setObjectName("pushButton_09")
        self.horizontalLayout.addWidget(self.pushButton_09)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_10.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_11.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_12.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_14.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_2.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_15.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_2.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_16.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_17.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_2.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_18.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_18.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_18.setCheckable(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_2.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_19.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_2.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_20.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_2.addWidget(self.pushButton_20)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_21.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_21.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_21.setCheckable(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_3.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_22.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_22.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_22.setCheckable(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_3.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_23.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_23.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_23.setCheckable(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_3.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_24.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_24.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_3.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_25.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_25.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_25.setCheckable(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_3.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_26.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_26.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_26.setCheckable(True)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_3.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_27.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_27.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_27.setCheckable(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_3.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_28.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_28.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_28.setCheckable(True)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_3.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_29.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_29.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_29.setCheckable(True)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_3.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_30.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_30.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_30.setCheckable(True)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_3.addWidget(self.pushButton_30)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_31.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_31.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_31.setCheckable(True)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_4.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_32.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_32.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_32.setCheckable(True)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_4.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_33.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_33.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_33.setCheckable(True)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_4.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_34.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_34.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_34.setCheckable(True)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_4.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_35.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_35.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_35.setCheckable(True)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_4.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_36.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_36.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_36.setCheckable(True)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_4.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_37.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_37.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_37.setCheckable(True)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_4.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_38.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_38.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_38.setCheckable(True)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_4.addWidget(self.pushButton_38)
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_39.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_39.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_39.setCheckable(True)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_4.addWidget(self.pushButton_39)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButton_Gen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Gen.setMinimumSize(QtCore.QSize(160, 80))
        self.pushButton_Gen.setMaximumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Gen.setFont(font)
        self.pushButton_Gen.setObjectName("pushButton_Gen")
        self.horizontalLayout_6.addWidget(self.pushButton_Gen)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Combinations"))
        self.label.setText(_translate("MainWindow", "Numbers"))
        self.pushButton_Random.setText(_translate("MainWindow", "Random"))
        self.groupBox.setTitle(_translate("MainWindow", "Numbers"))
        self.pushButton_01.setText(_translate("MainWindow", "01"))
        self.pushButton_02.setText(_translate("MainWindow", "02"))
        self.pushButton_03.setText(_translate("MainWindow", "03"))
        self.pushButton_04.setText(_translate("MainWindow", "04"))
        self.pushButton_05.setText(_translate("MainWindow", "05"))
        self.pushButton_06.setText(_translate("MainWindow", "06"))
        self.pushButton_07.setText(_translate("MainWindow", "07"))
        self.pushButton_08.setText(_translate("MainWindow", "08"))
        self.pushButton_09.setText(_translate("MainWindow", "09"))
        self.pushButton_10.setText(_translate("MainWindow", "10"))
        self.pushButton_11.setText(_translate("MainWindow", "11"))
        self.pushButton_12.setText(_translate("MainWindow", "12"))
        self.pushButton_13.setText(_translate("MainWindow", "13"))
        self.pushButton_14.setText(_translate("MainWindow", "14"))
        self.pushButton_15.setText(_translate("MainWindow", "15"))
        self.pushButton_16.setText(_translate("MainWindow", "16"))
        self.pushButton_17.setText(_translate("MainWindow", "17"))
        self.pushButton_18.setText(_translate("MainWindow", "18"))
        self.pushButton_19.setText(_translate("MainWindow", "19"))
        self.pushButton_20.setText(_translate("MainWindow", "20"))
        self.pushButton_21.setText(_translate("MainWindow", "21"))
        self.pushButton_22.setText(_translate("MainWindow", "22"))
        self.pushButton_23.setText(_translate("MainWindow", "23"))
        self.pushButton_24.setText(_translate("MainWindow", "24"))
        self.pushButton_25.setText(_translate("MainWindow", "25"))
        self.pushButton_26.setText(_translate("MainWindow", "26"))
        self.pushButton_27.setText(_translate("MainWindow", "27"))
        self.pushButton_28.setText(_translate("MainWindow", "28"))
        self.pushButton_29.setText(_translate("MainWindow", "29"))
        self.pushButton_30.setText(_translate("MainWindow", "30"))
        self.pushButton_31.setText(_translate("MainWindow", "31"))
        self.pushButton_32.setText(_translate("MainWindow", "32"))
        self.pushButton_33.setText(_translate("MainWindow", "33"))
        self.pushButton_34.setText(_translate("MainWindow", "34"))
        self.pushButton_35.setText(_translate("MainWindow", "35"))
        self.pushButton_36.setText(_translate("MainWindow", "36"))
        self.pushButton_37.setText(_translate("MainWindow", "37"))
        self.pushButton_38.setText(_translate("MainWindow", "38"))
        self.pushButton_39.setText(_translate("MainWindow", "39"))
        self.pushButton_Gen.setText(_translate("MainWindow", "Generate"))

